### ISSUE TITLE
how can i change geometry

### ISSUE THREAD

**Issue by dandelions** [wardwouts/koreader-novnc#1]
Nice project !
I'm thinking about how to change geometry, can you help me

**Comment by wardwouts** [comment]
That's a very good idea. I've implemented a GEOMETRY environment variable (see the README.md) and pushed a new image to dockerhub.

**Comment by wardwouts** [comment]
I just realized I only fixed half the issue. I also need to set the size of the koreader app itself

**Comment by wardwouts** [comment]
I think it's fixed correctly now. Can you check? The environment variable changed, so please check the README.md on how to use it.
