### ISSUE TITLE
[Feature request] arm64 image (like to run it on a Raspberry Pi 4)?

### ISSUE THREAD

**Issue by garret** [wardwouts/koreader-novnc#2]
Hi, would it be possible to also get an `arm64` image so that it could run on a Raspberry pi 4? 
I know there is a new tool from docker called `buildx` that should be able to build images also for other architectures automatically (but I am quite noob with such stuff).

**Comment by wardwouts** [comment]
I'm looking into this. Apparently it should also be possible with podman/buildah.

**Comment by wardwouts** [comment]
Automating this will still need work, but I've just manually pushed an arm64 image. Can you check if it works for you?

**Comment by wardwouts** [comment]
It is showing up for both amd64 and arm64 now: https://hub.docker.com/r/wardwouts/koreader-novnc/tags
